CREATE DATABASE Wish_List;
GO

USE Wish_List;
GO

CREATE TABLE USUARIOS (
	   idUsuarios SMALLINT PRIMARY KEY IDENTITY(1,1),
	   email VARCHAR(256) UNIQUE NOT NULL,
	   senha VARCHAR(10) NOT NULL
);
GO

CREATE TABLE DESEJOS (
	   idDesejos SMALLINT PRIMARY KEY IDENTITY(1,1),
	   idUsuarios  SMALLINT FOREIGN KEY REFERENCES USUARIOS(idUsuarios),
	   nomeDesejo VARCHAR(100) NOT NULL,
	   descricao VARCHAR(256) NOT NULL
);
GO